export const FETCH_BOOKS_START = 'FETCH_BOOKS_START';
export const FETCH_BOOKS = 'FETCH_BOOKS';
export const FETCH_BOOKS_FAILED = 'FETCH_BOOKS_FAILED';

export const FETCH_BOOK_START = 'FETCH_BOOK_START';
export const FETCH_BOOK = 'FETCH_BOOK';
export const FETCH_BOOK_FAILED = 'FETCH_BOOK_FAILED';

export const EDIT_BOOK_START = 'EDIT_BOOK_START';
export const EDIT_BOOK = 'EDIT_BOOK';
export const EDIT_BOOK_FAILED = 'EDIT_BOOK_FAILED';

export const ADD_BOOK_START = 'ADD_BOOK_START';
export const ADD_BOOK = 'ADD_BOOK';
export const ADD_BOOK_FAILED = 'ADD_BOOK_FAILED';

export const DELETE_BOOK_START = 'DELETE_BOOK_START';
export const DELETE_BOOK = 'DELETE_BOOK';
export const DELETE_BOOK_FAILED = 'DELETE_BOOK_FAILED';
export const BOOK_TO_BE_DELETED = 'BOOK_TO_BE_DELETED';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_EMAIL = 'AUTH_EMAIL';
export const AUTH_START = 'AUTH_START';

export const CART_CONTENTS = 'CART_CONTENTS';

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const OPEN_FIND_BOOK_DROPDOWN = 'OPEN_FIND_BOOK_DROPDOWN';
export const CLOSE_FIND_BOOK_DROPDOWN = 'CLOSE_FIND_BOOK_DROPDOWN';

export const SEARCH_STARTED = 'SEARCH_STARTED';
export const SEARCH_STOPPED = 'SEARCH_STOPPED';

export const SAVE_ORDER_START = 'SAVE_ORDER_START';
export const SAVE_ORDER = 'SAVE_ORDER';
export const SAVE_ORDER_FAILED = 'SAVE_ORDER_FAILED';
export const SAVE_SUCCESS = 'SAVE_SUCCESS';

export const FETCH_MY_ORDERS_START = 'FETCH_MY_ORDERS_START';
export const FETCH_MY_ORDERS = 'FETCH_MY_ORDERS';
export const FETCH_MY_ORDERS_FAILED = 'FETCH_MY_ORDERS_FAILED';
